-- =====================================================================
-- XAVAGE STOCK SIM :: 0007 -- seed settings + starter universe
-- =====================================================================

insert into public.game_settings (id) values (true) on conflict (id) do nothing;

-- Sensible competition defaults: cash-only, long-only, small friction.
update public.game_settings set
  starting_capital        = coalesce(nullif(starting_capital, 0), 1000000),
  commission_bps          = 2,       -- 0.02% per trade
  min_commission          = 1,
  slippage_bps            = 3,       -- 0.03% market-order spread cost
  allow_shorting          = false,
  allow_margin            = false,
  max_leverage            = 1.0,
  cash_interest_apr       = 4.0,     -- idle cash earns; an admin lever mid-game
  margin_interest_apr     = 9.0,
  short_borrow_apr        = 3.0,
  max_position_pct_of_equity = 25,   -- forces diversification
  market_hours_mode       = 'regular',
  price_staleness_seconds = 900
where id;

-- Starter universe. The Python worker enriches names/sectors and can add
-- any other yfinance-resolvable ticker on demand.
insert into public.instruments (symbol, name, exchange, asset_type, sector) values
  ('AAPL','Apple Inc.','NASDAQ','EQUITY','Technology'),
  ('MSFT','Microsoft Corporation','NASDAQ','EQUITY','Technology'),
  ('NVDA','NVIDIA Corporation','NASDAQ','EQUITY','Technology'),
  ('GOOGL','Alphabet Inc. Class A','NASDAQ','EQUITY','Communication Services'),
  ('AMZN','Amazon.com Inc.','NASDAQ','EQUITY','Consumer Cyclical'),
  ('META','Meta Platforms Inc.','NASDAQ','EQUITY','Communication Services'),
  ('TSLA','Tesla Inc.','NASDAQ','EQUITY','Consumer Cyclical'),
  ('AVGO','Broadcom Inc.','NASDAQ','EQUITY','Technology'),
  ('AMD','Advanced Micro Devices Inc.','NASDAQ','EQUITY','Technology'),
  ('INTC','Intel Corporation','NASDAQ','EQUITY','Technology'),
  ('NFLX','Netflix Inc.','NASDAQ','EQUITY','Communication Services'),
  ('ADBE','Adobe Inc.','NASDAQ','EQUITY','Technology'),
  ('CRM','Salesforce Inc.','NYSE','EQUITY','Technology'),
  ('ORCL','Oracle Corporation','NYSE','EQUITY','Technology'),
  ('CSCO','Cisco Systems Inc.','NASDAQ','EQUITY','Technology'),
  ('QCOM','QUALCOMM Incorporated','NASDAQ','EQUITY','Technology'),
  ('TXN','Texas Instruments Inc.','NASDAQ','EQUITY','Technology'),
  ('MU','Micron Technology Inc.','NASDAQ','EQUITY','Technology'),
  ('PLTR','Palantir Technologies Inc.','NASDAQ','EQUITY','Technology'),
  ('UBER','Uber Technologies Inc.','NYSE','EQUITY','Technology'),
  ('SHOP','Shopify Inc.','NYSE','EQUITY','Technology'),
  ('XYZ','Block, Inc.','NYSE','EQUITY','Technology'),   -- formerly SQ; reticker'd
  ('COIN','Coinbase Global Inc.','NASDAQ','EQUITY','Financial Services'),
  ('SNOW','Snowflake Inc.','NYSE','EQUITY','Technology'),
  ('ABNB','Airbnb Inc.','NASDAQ','EQUITY','Consumer Cyclical'),
  ('JPM','JPMorgan Chase & Co.','NYSE','EQUITY','Financial Services'),
  ('BAC','Bank of America Corporation','NYSE','EQUITY','Financial Services'),
  ('WFC','Wells Fargo & Company','NYSE','EQUITY','Financial Services'),
  ('GS','Goldman Sachs Group Inc.','NYSE','EQUITY','Financial Services'),
  ('MS','Morgan Stanley','NYSE','EQUITY','Financial Services'),
  ('C','Citigroup Inc.','NYSE','EQUITY','Financial Services'),
  ('BLK','BlackRock Inc.','NYSE','EQUITY','Financial Services'),
  ('V','Visa Inc.','NYSE','EQUITY','Financial Services'),
  ('MA','Mastercard Incorporated','NYSE','EQUITY','Financial Services'),
  ('AXP','American Express Company','NYSE','EQUITY','Financial Services'),
  ('PYPL','PayPal Holdings Inc.','NASDAQ','EQUITY','Financial Services'),
  ('BRK-B','Berkshire Hathaway Inc. Class B','NYSE','EQUITY','Financial Services'),
  ('JNJ','Johnson & Johnson','NYSE','EQUITY','Healthcare'),
  ('UNH','UnitedHealth Group Inc.','NYSE','EQUITY','Healthcare'),
  ('LLY','Eli Lilly and Company','NYSE','EQUITY','Healthcare'),
  ('PFE','Pfizer Inc.','NYSE','EQUITY','Healthcare'),
  ('MRK','Merck & Co. Inc.','NYSE','EQUITY','Healthcare'),
  ('ABBV','AbbVie Inc.','NYSE','EQUITY','Healthcare'),
  ('TMO','Thermo Fisher Scientific Inc.','NYSE','EQUITY','Healthcare'),
  ('ABT','Abbott Laboratories','NYSE','EQUITY','Healthcare'),
  ('AMGN','Amgen Inc.','NASDAQ','EQUITY','Healthcare'),
  ('CVS','CVS Health Corporation','NYSE','EQUITY','Healthcare'),
  ('MRNA','Moderna Inc.','NASDAQ','EQUITY','Healthcare'),
  ('WMT','Walmart Inc.','NYSE','EQUITY','Consumer Defensive'),
  ('COST','Costco Wholesale Corporation','NASDAQ','EQUITY','Consumer Defensive'),
  ('PG','Procter & Gamble Company','NYSE','EQUITY','Consumer Defensive'),
  ('KO','Coca-Cola Company','NYSE','EQUITY','Consumer Defensive'),
  ('PEP','PepsiCo Inc.','NASDAQ','EQUITY','Consumer Defensive'),
  ('MCD','McDonald''s Corporation','NYSE','EQUITY','Consumer Cyclical'),
  ('SBUX','Starbucks Corporation','NASDAQ','EQUITY','Consumer Cyclical'),
  ('NKE','NIKE Inc.','NYSE','EQUITY','Consumer Cyclical'),
  ('HD','Home Depot Inc.','NYSE','EQUITY','Consumer Cyclical'),
  ('LOW','Lowe''s Companies Inc.','NYSE','EQUITY','Consumer Cyclical'),
  ('TGT','Target Corporation','NYSE','EQUITY','Consumer Defensive'),
  ('DIS','Walt Disney Company','NYSE','EQUITY','Communication Services'),
  ('CMCSA','Comcast Corporation','NASDAQ','EQUITY','Communication Services'),
  ('T','AT&T Inc.','NYSE','EQUITY','Communication Services'),
  ('VZ','Verizon Communications Inc.','NYSE','EQUITY','Communication Services'),
  ('XOM','Exxon Mobil Corporation','NYSE','EQUITY','Energy'),
  ('CVX','Chevron Corporation','NYSE','EQUITY','Energy'),
  ('COP','ConocoPhillips','NYSE','EQUITY','Energy'),
  ('SLB','Schlumberger Limited','NYSE','EQUITY','Energy'),
  ('OXY','Occidental Petroleum Corporation','NYSE','EQUITY','Energy'),
  ('BA','Boeing Company','NYSE','EQUITY','Industrials'),
  ('CAT','Caterpillar Inc.','NYSE','EQUITY','Industrials'),
  ('GE','GE Aerospace','NYSE','EQUITY','Industrials'),
  ('HON','Honeywell International Inc.','NASDAQ','EQUITY','Industrials'),
  ('UPS','United Parcel Service Inc.','NYSE','EQUITY','Industrials'),
  ('RTX','RTX Corporation','NYSE','EQUITY','Industrials'),
  ('LMT','Lockheed Martin Corporation','NYSE','EQUITY','Industrials'),
  ('DE','Deere & Company','NYSE','EQUITY','Industrials'),
  ('F','Ford Motor Company','NYSE','EQUITY','Consumer Cyclical'),
  ('GM','General Motors Company','NYSE','EQUITY','Consumer Cyclical'),
  ('DAL','Delta Air Lines Inc.','NYSE','EQUITY','Industrials'),
  ('LIN','Linde plc','NASDAQ','EQUITY','Basic Materials'),
  ('NEM','Newmont Corporation','NYSE','EQUITY','Basic Materials'),
  ('FCX','Freeport-McMoRan Inc.','NYSE','EQUITY','Basic Materials'),
  ('NEE','NextEra Energy Inc.','NYSE','EQUITY','Utilities'),
  ('DUK','Duke Energy Corporation','NYSE','EQUITY','Utilities'),
  ('SO','Southern Company','NYSE','EQUITY','Utilities'),
  ('AMT','American Tower Corporation','NYSE','EQUITY','Real Estate'),
  ('PLD','Prologis Inc.','NYSE','EQUITY','Real Estate'),
  ('SPY','SPDR S&P 500 ETF Trust','NYSEARCA','ETF','Index'),
  ('QQQ','Invesco QQQ Trust','NASDAQ','ETF','Index'),
  ('DIA','SPDR Dow Jones Industrial Average ETF','NYSEARCA','ETF','Index'),
  ('IWM','iShares Russell 2000 ETF','NYSEARCA','ETF','Index'),
  ('VTI','Vanguard Total Stock Market ETF','NYSEARCA','ETF','Index'),
  ('VOO','Vanguard S&P 500 ETF','NYSEARCA','ETF','Index'),
  ('ARKK','ARK Innovation ETF','NYSEARCA','ETF','Thematic'),
  ('XLE','Energy Select Sector SPDR Fund','NYSEARCA','ETF','Sector'),
  ('XLF','Financial Select Sector SPDR Fund','NYSEARCA','ETF','Sector'),
  ('XLK','Technology Select Sector SPDR Fund','NYSEARCA','ETF','Sector'),
  ('GLD','SPDR Gold Shares','NYSEARCA','ETF','Commodity'),
  ('SLV','iShares Silver Trust','NYSEARCA','ETF','Commodity'),
  ('USO','United States Oil Fund','NYSEARCA','ETF','Commodity'),
  ('TLT','iShares 20+ Year Treasury Bond ETF','NASDAQ','ETF','Fixed Income')
on conflict (symbol) do update
  set name = excluded.name,
      exchange = coalesce(excluded.exchange, public.instruments.exchange),
      sector = coalesce(excluded.sector, public.instruments.sector);
